[package]
name = "houtamelo_utils"
version = "1.1.0"
authors = ["Houtamelo"]
edition = "2021"
description = "A collection of utilities shared between Houtamelo's projects."
license = "MIT"
repository = "https://github.com/Houtamelo/houtamelo_utils"

[lib]
crate-type = ["lib"]

[dependencies]
float-cmp = { version = "0.9", features = ["std"] }
serde = { version = "1.0", features = ["derive"] }
ron = "0.8"
num-traits = "0.2"
serde_json = "1.0"
bimap = { version = "0.6", features = ["serde", "std"] }
rand = "0.8"
