[package]
name = "houtamelo_utils"
version = "1.0.0"
authors = ["Houtamelo"]
edition = "2021"

[lib]
crate-type = ["lib"]

[dependencies]
float-cmp = { version = "0.9.0", features = ["std"] }
serde = { version = "1.0.193", features = ["derive"] }
ron = "0.8.1"
